{
    "name": "Veterinary Clinic",
    "version": "17.0.1.0.0",
    "category": "Healthcare",
    "summary": """
        Veterinary clinic management system with patient records,
        appointments, and resource booking
    """,
    "author": "veterinarian",
    "website": "https://github.com/veterinarian/vet-odoo",
    "license": "AGPL-3",
    "depends": [
        "base",
        "mail",
        "calendar",
        "resource_booking",
    ],
    "data": [
        "security/vet_clinic_security.xml",
        "security/ir.model.access.csv",
        "data/vet_species_data.xml",
        "data/vet_provider_type_data.xml",
        "data/vet_room_data.xml",
        "data/resource_booking_type_data.xml",
        "views/vet_provider_type_views.xml",
        "views/vet_room_views.xml",
        "views/res_users_views.xml",
        "views/vet_owner_views.xml",
        "views/resource_booking_views.xml",
        "views/vet_appointment_views.xml",
        "views/vet_medical_note_views.xml",
        "views/vet_problem_views.xml",
        "views/vet_patient_views.xml",
        "views/vet_menu.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "vet_clinic/static/src/js/medical_timeline.js",
            "vet_clinic/static/src/xml/medical_timeline.xml",
            "vet_clinic/static/src/css/medical_timeline.css",
        ],
    },
    "demo": [],
    "installable": True,
    "application": True,
    "auto_install": False,
    "post_init_hook": "post_init_hook",
}
